# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib(n)
    return n if n <= 1
    arr = [0,1]
    i=2
    evenSum = 0
    loop do
        arr[i] = arr[i-2] + arr[i-1]
        evenSum += arr[i] if arr[i] % 2 == 0
        i+=1
        break if i >= n+2
    end
    evenSum
end

def recursiveFib(n)
    sum = 0
    return n if n<=2 
    recursiveFib(n-2) + recursiveFib(n-1)
end


puts fib(10)
# puts recursiveFib(10)